// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlYhPCUXe5z5eZ7kagUb_VYa5ElUd5M8',
    appId: '1:639829727465:web:913bf4650b4deb4f9c3878',
    messagingSenderId: '639829727465',
    projectId: 'marwox-a53e6',
    authDomain: 'marwox-a53e6.firebaseapp.com',
    storageBucket: 'marwox-a53e6.firebasestorage.app',
    measurementId: 'G-CRFN2BPB2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv0kVqlXvtjswJq0TZq1xI7uMSzPWf_jU',
    appId: '1:639829727465:android:cb3443ac2b6365279c3878',
    messagingSenderId: '639829727465',
    projectId: 'marwox-a53e6',
    storageBucket: 'marwox-a53e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE5enEMYnQEudm0lITBdweEeM05m2qB-E',
    appId: '1:639829727465:ios:ef731fba26f0b4249c3878',
    messagingSenderId: '639829727465',
    projectId: 'marwox-a53e6',
    storageBucket: 'marwox-a53e6.firebasestorage.app',
    iosBundleId: 'com.example.marworxFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlYhPCUXe5z5eZ7kagUb_VYa5ElUd5M8',
    appId: '1:639829727465:web:b4de904eda5d6f479c3878',
    messagingSenderId: '639829727465',
    projectId: 'marwox-a53e6',
    authDomain: 'marwox-a53e6.firebaseapp.com',
    storageBucket: 'marwox-a53e6.firebasestorage.app',
    measurementId: 'G-MJK14H52NM',
  );
}
